# Generated by Django 4.1.5 on 2023-01-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('cert_url', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_employee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.CharField(max_length=50)),
                ('is_opensource', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('is_public', models.BooleanField()),
                ('date_added', models.DateField()),
                ('date_updated', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education'},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='updated_at',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='ended_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='started_at',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='degree_name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='education',
            name='is_completed',
            field=models.CharField(max_length=50),
        ),
    ]
