# Generated by Django 4.1.5 on 2023-01-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0002_certification_job_project_skill_socialmedia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social Media'},
        ),
    ]
