# Generated by Django 4.1.5 on 2023-01-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0003_alter_socialmedia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
