# Generated by Django 4.1.5 on 2023-01-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0005_alter_education_options_alter_socialmedia_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='cert_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='is_published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='is_completed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_opensource',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
