# Generated by Django 4.1.5 on 2023-02-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0008_portfolio_repository_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_opensource',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
