# Generated by Django 4.1.5 on 2023-02-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0009_project_is_opensource_project_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_link',
            field=models.URLField(blank=True),
        ),
    ]
