# Generated by Django 4.1.5 on 2023-02-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0010_project_repository_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Virginia, United States', max_length=200),
            preserve_default=False,
        ),
    ]
