# Generated by Django 4.1.5 on 2023-02-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0011_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default='Miranda, Venezuela', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
