# Generated by Django 4.1.5 on 2023-02-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0012_education_location_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='is_completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='is_opensource',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(),
        ),
    ]
