# Generated by Django 4.1.5 on 2023-02-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0014_alter_education_university_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_dropped',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
