# Generated by Django 4.1.5 on 2023-03-11 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_websites', '0016_category_interest_proficiency_skill_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
