# Generated by Django 4.1.5 on 2023-03-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.RemoveField(
            model_name='repository',
            name='is_opensource',
        ),
    ]
