# Generated by Django 4.1.5 on 2023-03-11 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_repository_is_opensource_alter_repository_is_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='created_at',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='updated_at',
            new_name='date_updated',
        ),
    ]
