# Generated by Django 4.1.5 on 2023-03-11 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_rename_created_at_repository_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='repository',
            old_name='date_updated',
            new_name='updated_at',
        ),
    ]
