# Generated by Django 4.1.5 on 2023-03-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0005_rename_date_added_repository_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
