# Generated by Django 4.1.5 on 2023-04-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0008_remove_repository_is_opensource_repository_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='pushed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
